//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDBLab29.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieList
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public int Runtime { get; set; }
        public string Rating { get; set; }
        public string Director { get; set; }
    }
}
